id: A966D4DB1
title: Prayer to the Lineage of Lumorab
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:33:43.329322
  last_modified_at: 2022-02-28 23:33:43.329330
